var _AddressBestMatchFound = ""; $(document).ready(function () { RealTimAddressVerificationEventHandler(); HideStateInputBoxForCountryWithState("AddressControl"); HideStateInputBoxForCountryWithState("ShippingAddressControl"); HideStateInputBoxForCountryWithState("BillingAddressControl"); AjaxCallCommon("ActionService.asmx/GetCity", { countryCode: "", postalCode: "", stateCode: "" }, function () { }, function (a) { }) });
function RealTimAddressVerificationEventHandler() {
    $("#select-entered-address").click(function () { var a = _AddressBestMatchFound.split("::"), d = a[4]; a[5] && ISEAddressVerificationTaskSelector(d) }); $("#select-matching-address").click(function () {
        var a = _AddressBestMatchFound.split("::"), d = a[0], b = a[1], c = a[2], f = a[3], e = a[4], g = a[5], a = a[6]; d && b && c && f && ($("#" + a + "AddressControl_txtStreet").val(d), $("#" + a + "AddressControl_txtPostal").val(b), $("#" + a + "AddressControl_txtCity").val(c), $("#" + a + "AddressControl_txtState").val(f));
        g && ISEAddressVerificationTaskSelector(e)
    })
}
function RenderCityStates(a, d, b) {
    var c = "#" + b + "AddressControl_drpCountry", f = "#" + b + "AddressControl_txtPostal", e = "#" + b + "AddressControl_txtState", g = ".zip-city-other-place-holder", m = "#enter-postal-label-place-holder"; "" != b && (b.toLowerCase(), g = "." + b.toLowerCase() + "-zip-city-other-place-holder", m = "#" + b.toLowerCase() + "-enter-postal-label-place-holder"); var h = $(g).css("display"), h = h.toLowerCase(); if ("" == $(f).val() && ("none" != h || "" != h)) return $(g).fadeOut("Slow", function () { $(m).html(ise.StringResource.getString("customersupport.aspx.40")); $("#ise-message-tips").fadeOut("fast") }),
    !1; if ("none" != h || "" == h) return !1; c = $(c).val(); g = $(f).val(); e = $(e).val(); a && (e = ""); IsPostalFormatInvalid(c, g) ? ($(f).addClass("support-invalid-postal"), $(m).html(ise.StringResource.getString("customersupport.aspx.40")), d && $(f).focus()) : ($(f).removeClass("support-invalid-postal"), SearchForCityAndState(c, _PostalCode, e, d, b))
}
function SearchForCityAndState(a, d, b, c, f) {
    var e = {}; e.countryCode = a; e.postalCode = d; e.stateCode = b; AjaxCallCommon("ActionService.asmx/GetCity", e, function (a) {
        var b = "#" + f + "AddressControl_txtPostal", d = "city-states", e = ".zip-city-other-place-holder", k = "#enter-postal-label-place-holder"; "" != f && (d = f.toLowerCase() + "-city-states", e = "." + f.toLowerCase() + "-zip-city-other-place-holder", k = "#" + f.toLowerCase() + "-enter-postal-label-place-holder"); if ("" != a.d) {
            var l = "<select id='" + d + "' class='light-style-input'>", l = l +
            a.d, l = l + ("<option value='other'>" + ise.StringResource.getString("customersupport.aspx.41") + "</option>"), l = l + "</select>"; 0 < a.d.length ? $(e).fadeOut("Slow", function () { $(k).html(l) }) : ($(k).html(ise.StringResource.getString("customersupport.aspx.40")), c && $(b).focus()); $("#" + d + "").change(function () { "other" == $(this).val() && ($(this).fadeOut("Slow", function () { $(e).fadeIn("Slow") }), HideStateInputBoxForCountryWithState(f + "AddressControl")) }); $(b).removeClass("invalid-postal-zero")
        } else $(k).html(ise.StringResource.getString("customersupport.aspx.40")),
        $(b).addClass("invalid-postal-zero"), c && $(b).focus()
    }, function () { })
} function IsCountryWithStates(a) { var d = $(a).attr("class"), b = ""; "undefined" != typeof d && (a = d.split(" ")[0].split("-")[$(a).prop("selectedIndex")], a = a.split("::"), b = a[0]); return b.toLowerCase() } function IsCountrySearchable(a) { a = $(a).attr("class").split(" ")[0].split("-")[$(a).prop("selectedIndex")]; a = a.split("::"); return a[1].toLowerCase() }
function VerifyPostalCode(a, d, b, c, f, e, g) { if ($(e).hasClass("skip")) return $(e).removeClass("invalid-postal-zero"), PageSubmitProcess(g), !0; c = {}; c.countryCode = a; c.postalCode = d; c.stateCode = ""; AjaxCallCommon("ActionService.asmx/IsPostalCodeValid", c, function (a) { !1 != a.d ? ($(e).removeClass("invalid-postal-zero"), !0 == f && 0 == IsAddressConrolBad() && PageSubmitProcess(g)) : ($(e).addClass("invalid-postal-zero"), b && $(e).focus()) }, function () { }) }
function VerifyStateCode(a, d, b, c, f, e) { var g = {}; g.countryCode = a; g.postalCode = d; g.stateCode = b; AjaxCallCommon("ActionService.asmx/IsStateCodeValid", g, function (a) { !1 == a.d ? ($(e).addClass("state-not-found"), !0 == c && ($(e).addClass("current-object-on-focus"), $(e).focus())) : ($(e).removeClass("state-not-found"), !0 == c && PageSubmitProcess(f)); return a.d }, function () { return 0 }) }
function IsShippingStateCodeIsGood(a, d, b) { var c = {}; c.countryCode = a; c.postalCode = d; c.stateCode = b; AjaxCallCommon("ActionService.asmx/GetCity", c, function (a) { if ("0" == a.d) return $("#shipping-states-input").addClass("support-state-not-found"), !1; $("#shipping-states-input").removeClass("support-state-not-found"); return !0 }, function () { return !1 }) }
function GetCountryPostalFormats(a, d) { [].push("united states of america"); var b = []; b.push("12345-6789"); return "united states of america" != a.toLowerCase() ? "free-form" : b[0] }
function IsPostalFormatInvalid(a, d) { var b = GetCountryPostalFormats(a, d), c; c = b.split("-"); if (0 < c.length && "free-form" != b) if (b = d.split("-"), _PostalCode = b[0], 1 < b.length) { if (b.length != c.length) return !0; for (var f = 0; f < b.length; f++) { var e = b[f].length; if (e != c[f].length || 0 == e) return !0 } } else { if (_PostalCode = d, 0 == d.length || d.length != c[0].length) return !0 } else _PostalCode = d; return !1 }
function ValidateAddressDetails(a, d, b, c, f) {
    var e = "#" + c + "AddressControl_drpCountry", g = "#" + c + "AddressControl_txtPostal", m = "#" + c + "AddressControl_txtState", h = "#" + c + "AddressControl_txtState", q = "#city-states", k = ".zip-city-other-place-holder", l = "#enter-postal-label-place-holder"; "" != c && (q = "#" + c.toLowerCase() + "-city-states", k = "." + c.toLowerCase() + "-zip-city-other-place-holder", l = "#" + c.toLowerCase() + "-enter-postal-label-place-holder"); var n = $(k).css("display"), n = n.toLowerCase(), k = $(e).val(), p = $(g).val(), r =
    $(g).hasClass("is-postal-optional") && "" == p; if ("true" == IsCountrySearchable(e) && !1 == r) { if (IsPostalFormatInvalid(k, p)) return $(g).addClass("invalid-postal"), "none" == n && $(l).html(ise.StringResource.getString("customersupport.aspx.40")), a && $(g).focus(), !1 } else return PageSubmitProcess(f), !0; _prevPostal = _currentPostal; _currentPostal = p; e = $(q).val(); "other" == e ? b ? VerifyPostalCode(k, _PostalCode, a, b, d, g, f) : (a = $(m).val(), VerifyStateCode(k, _PostalCode, a, !0, f, h)) : ("none" != n || !1 != d || "undefined" != typeof e && _prevPostal ==
    _currentPostal || RenderCityStates(!0, a, c), !0 == d && VerifyPostalCode(k, _PostalCode, a, b, d, g, f))
} function IsAddressConrolBad() { var a = $(".invalid-postal-zero").length, d = $(".invalid-postal").length, b = $(".state-not-found").length, c = $(".required-input").length; return a + d + b + c }
function PageSubmitProcess(a) {
    switch (a) {
        case "case-form": a = ["errorSummary", "save-case-loader", "save-case-button-place-holder"]; ISEAddressVerification(!0, "case-form", "", !1, a); break; case "lead-form": a = ["errorSummary", "save-lead-loader", "save-lead-button-place-holder"]; ISEAddressVerification(!0, "lead-form", "", !1, a); break; case "add-address": a = ["errorSummary", "save-address-loader", "save-address-button-place-holder"]; ISEAddressVerification(!0, "add-address", "", !1, a); break; case "update-address": a = ["errorSummary",
        "update-address-loader", "update-address-button-place-holder"]; ISEAddressVerification(!0, "update-address", "", !1, a); break; case "shipping-calculator": DoSubmissionOfShippingCalculatorAction()
    }
} function GetAddressVerificationGatewayError(a) { a = a.d.split("[error]"); return 1 < a.length ? $.trim(a[1]) : "" }
function ClearAddressControl() {
    $("#shipping-address-input").val(""); $("#shipping-postal-code-input").val(""); $("#shipping-city-input").val(""); $("#shipping-states-input").val(""); $("#shipping-address-input-label").removeClass("display-none"); $("#shipping-postal-code-input-label").removeClass("display-none"); $("#shipping-city-input-label").removeClass("display-none"); $("#shipping-states-input-label").removeClass("display-none"); $("#shipping-address-input-label").css("color", labelFadeInColor); $("#shipping-postal-code-input-label").css("color",
    labelFadeInColor); $("#shipping-city-input-label").css("color", labelFadeInColor); $("#shipping-states-input-label").css("color", labelFadeInColor); $("#shipping-address-input").removeClass("support-required-input"); $("#shipping-city-input").removeClass("support-required-input"); $("#shipping-states-input").removeClass("support-required-input"); $("#shipping-postal-code-input").removeClass("support-required-input"); $("#shipping-postal-code-input").removeClass("support-invalid-postal"); $("#shipping-postal-code-input").removeClass("support-current-input-on-focus")
}
function UpdateAddressInfo(a, d, b, c, f) {
    $("#ise-message-tips").fadeOut("slow"); var e = "#" + a + "AddressControl_txtStreet", g = "#" + a + "AddressControl_txtCity", m = "#" + a + "AddressControl_txtState", h = "#" + a + "AddressControl_txtPostal"; $(e).removeClass("required-input"); $(g).removeClass("required-input"); $(m).removeClass("required-input"); $(h).removeClass("required-input"); $(h).removeClass("invalid-postal"); $(h).removeClass("current-input-on-focus"); "" != d && ($("#" + a + "AddressControl_lblStreet").addClass("display-none"),
    $(e).val(d)); "" != b && ($("#" + a + "AddressControl_lblCity").addClass("display-none"), $(g).val(b)); "" != c && ($("#" + a + "AddressControl_lblState").addClass("display-none"), $(m).val(c)); "" != f && ($("#" + a + "AddressControl_lblPostal").addClass("display-none"), $(h).val(f))
}
function _SplitAreaCodeAndPhone(a, d, b) { var c = b.split(")"), f = "", e = ""; 1 < c.length ? (f = c[0], f = f.replace(")", ""), f = f.replace("(", ""), f = f.replace("+", ""), e = c[1]) : (c = b.replace("+", ""), 10 <= b.length ? (e = c.substring(3, b.length), f = c.substring(0, 3)) : (e = c, $("#" + d + "-label").removeClass("display-none"))); "" != f && ($("#" + a[0]).val($.trim(f)), $("#" + a[1]).addClass("display-none")); "" != e && ($("#" + d[0]).val($.trim(e)), $("#" + d[1]).addClass("display-none")) }
function HideStateInputBoxForCountryWithState(a) { var d = IsCountryWithStates("#" + a + "_drpCountry"); "undefined" != typeof d && "false" == d ? ($("#" + a + "_txtState").addClass("display-none"), $("#" + a + "_lblState").addClass("display-none"), $("#" + a + "_txtCity").addClass("city-width-if-no-state")) : ($("#" + a + "_txtState").removeClass("display-none"), $("#" + a + "_txtCity").removeClass("city-width-if-no-state")) };