var _DEFAULT_MESSAGE = "", _DOWNLOAD_CASE_MESSAGE = "";
$(document).ready(function () {
    GetStringResources("case-history"); _DEFAULT_MESSAGE = $("#_DEFAULT_MESSAGE").html(); _DOWNLOAD_CASE_MESSAGE = $("#_DOWNLOAD_CASE_MESSAGE").html(); RenderCaseHistory(); $("#support-select-view").change(function () { $("#support-search-text").val(""); RenderCaseHistory() }); $("#support-search-go").click(function () { $("#support-select-view").val(); $("#support-select-period").val(); $("#support-search-text").val(); RenderCaseHistory() }); $("#open-case").click(function () {
        if ($(this).hasClass("editable-content")) return !1;
        parent.location = "customersupport.aspx"
    }); $("#support-search-text").keypress(function (b) { if (13 == b.which) return $("#support-select-view").val(), $("#support-select-period").val(), $("#support-search-text").val(), RenderCaseHistory(), !1 }); $("#support-select-period").change(function () { $("#support-search-text").val(""); $("#support-select-view").val(); $("#support-select-period").val(); $("#support-search-text").val(); RenderCaseHistory() })
});
function RenderCaseHTML_OUTPUT(b) {
    var c = "", a = ""; b = $.parseJSON(b); for (var e = "", f = "", g = "", h = "", k = "", l = "", m = "", n = "", d = 0; d < b.length; d++) e = b[d].ActivityCode, f = b[d].SubjectShort, n = b[d].SubjectFull, g = b[d].Status, h = b[d].Priority, k = b[d].AssignedTo, l = b[d].ProblemText, m = b[d].SolutionText, a = "<div class='clear-both height-5'></div>", a += "<span id='activity-code-column-place-holder' class='capitalize-text'>" + ise.StringResource.getString("customersupport.aspx.44") + "</span> <span id='activity-code-value-place-holder'>" +
    e + "</span>", a += "<div class='clear-both'></div>", a += "<span id='priority-column-place-holder' class='capitalize-text'>" + ise.StringResource.getString("customersupport.aspx.45") + "</span> <span id='priority-value-place-holder'>" + h + "</span>", a += "<div class='clear-both'></div>", a += "<span id='assigned-to-column-place-holder' class='capitalize-text'>" + ise.StringResource.getString("customersupport.aspx.46") + "</span> <span id='assigned-to-value-place-holder'>" + k + "</span>", a += "<div class='clear-both height-12'></div>",
    a += "<span id='problem-text-column-place-holder' class='strong-font capitalize-text content' data-contentKey='customersupport.aspx.47' data-contentValue='" + ise.StringResource.getString("customersupport.aspx.47") + "' data-contentType='string resource'>" + ise.StringResource.getString("customersupport.aspx.47") + "</span>", a += "<div class='clear-both height-12'></div>", a += "<div class='p-details'>" + l + "</div>", a += "<div class='clear-both height-12'></div>", a += "<span id='field-solution-text-place-holder' class='strong-font capitalize-text content' data-contentKey='customersupport.aspx.48' data-contentValue='" +
    ise.StringResource.getString("customersupport.aspx.48") + "' data-contentType='string resource'>" + ise.StringResource.getString("customersupport.aspx.48") + "</span>", a += "<div class='clear-both height-12'></div>", a += "<div class='p-details'>" + m + "</div>", _detailsText = "<div class='support-case-details-wrapper' id='" + e + "-details'>" + a + "</div>", c += "<div class='support-list-row'>", c += "<div class='support-fields-date-started-value-container float-left'>" + b[d].DateCreated + "</div>", c += "<div class='support-fields-subject-value-container float-left'><a href='javascript:void(1)' class='case-subject-links' id='" +
    e + "' title='" + n + "'>" + f + "</a><div class='clear-both'></div>" + _detailsText + "</div>", c += "<div class='support-fields-status-value-container float-left'>" + g + "</div>", c += "</div>", c += "<div class='clear-both'></div>"; 0 == b.length && (c = "<div id='no-case-to-display'>No records found</div>"); return c
}
function RenderCaseHistory() {
    var b = $("#support-select-view").val(), c = $("#support-select-period").val(), a = $("#support-search-text").val(), e = _DOWNLOAD_CASE_MESSAGE; $("#support-grid-border-bottom").removeClass("error-message"); $("#support-grid-border-bottom").html("<div style='float:left;width:12px;'><img id='captcha-loader' src='images/ajax-loader.gif'></div> <div id='loader-container-to-right'>" + e + "</div>"); b = JSON.stringify({ activityStatus: b, period: c, searchString: a }); $.ajax({
        type: "POST", url: "ActionService.asmx/GetCaseHistory",
        data: b, contentType: "application/json; charset=utf-8", dataType: "json", success: function (a) { a = RenderCaseHTML_OUTPUT(a.d); $("#support-grid-details").html(a); $("#support-grid-border-bottom").html(""); bindCaseDetailsLink() }, fail: function (a) { $("#support-grid-border-bottom").addClass("error-message"); $("#support-grid-border-bottom").html(a.d) }
    })
}
function bindCaseDetailsLink() { $(".case-subject-links").click(function () { var b = $(this).attr("id"); $(".support-case-details-wrapper").fadeOut("Slow"); $("#" + b + "-details").fadeIn("Slow") }) };