var ProductReviewModel = {
    Comments: '',
    CompanyId: 0,
    CreatedOn: '',
    CustomerEmailAddress: '',
    CustomerName: '',
    FoundHelpful: 0,
    FoundNotHelpful: 0,
    HasComments: false,
    Helpful: 0,
    InventoryItemId: 0,
    IsActive: false,
    IsFilthy: false,
    IsRotd: false,
    MaskedWord: '',
    Rating: 0,
    RatingCustomerEmailAddress: '',
    RatingId: 0,
    RowIndex: 0,
    VotingCustomerEmailAddress: '',
    Word:''
};

//"Comments":"String content",
//"CompanyId":2147483647,
//"CreatedOn":"\/Date(928174800000-0700)\/",
//"CustomerEmailAddress":"String content",
//"CustomerName":"String content",
//"FoundHelpful":2147483647,
//"FoundNotHelpful":2147483647,
//"HasComments":true,
//"Helpful":2147483647,
//"InventoryItemId":2147483647,
//"IsActive":true,
//"IsFilthy":true,
//"IsRotd":true,
//"MaskedWord":"String content",
//"Rating":2147483647,
//"RatingCustomerEmailAddress":"String content",
//"RatingId":2147483647,
//"RowIndex":2147483647,
//"VotingCustomerEmailAddress":"String content",
//"Word":"String content"